feat: log an error summary in the message property
n-logger seems to expect a message field when logging, so we're now
providing a human-readable short summary of the error message in this
field. This does duplicate some data but will make error logs much
easier to quickly analyse in Splunk (the `error` property is collapsed
by default).

I decided to use both the error name and message so that you can also
tell if you're dealing with an operational error at a quick glance:

```
OperationalError: something expected went wrong
Error: something unexpected went wrong
```